### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by MathewSachin**
Cleaned up the project.

Please Compile and Test before merging.
- Moved .gitignore to repository root.
- Moved solution file and project to src folder.
- Updated ReadMe.
- Bass.Init/Free done in AppDelegate
- Using ManagedBass.PInvoke

### CODE REVIEW

**Comment by MathewSachin** [comment]
@bpieslak, The `Main.storyboard` seems very large. 
Particularly, it seems there are many unnecessary menu items (e.g. Spelling and Grammer, Edit, Format and more).
Pardon me if I'm wrong

**Comment by MathewSachin** [comment]
Did everything work fine?

Also, please see Main.storyboard. It seems unnecessarily large to me.

**Comment by bpieslak** [comment]
I had to update the .csproj file to get the application to compile and run within Xamarin Studio on my mac.  It works now.   I haven't looked at the Main.storyboard yet.  I can definitely remove the menu options that you noted (Spelling and Grammar, Edit, ...)  We don't need a toolbar in our example at all.

**Comment by bpieslak** [comment]
I just committed an update to Main.storyboard.  The file size is down to 13K.

**Comment by MathewSachin** [comment]
Great!  So we are ready to merge

**Comment by bpieslak** [comment]
I think so too.   Go ahead and hit the merge button if you want.  Or I can do it.  Either works for me.

**Pull request merged**
